name: Deploy

on:
  release:
    types:
      - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: containers.chewedfeed.com/retro-board/key-service
          tags: |
            type=semver,pattern={{version}}
            type=sha
      - name: DeplyMeta
        id: deploy-meta
        uses: docker/metadata-action@v3
        with:
          images: containers.chewedfeed.com/retro-board/key-service
          tags: |
            type=semver,pattern={{version}}
      - name: QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login Github
        uses: docker/login-action@v2
        with:
          registry: containers.chewedfeed.com
          username: robot$github
          password: ${{ secrets.CONTAINERS_KEY }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          builder: ${{ steps.buildx.outputs.name }}
          file: ./k8s/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          build-args: SERVICE_NAME=key-service,VERSION=${{ github.ref_name }},BUILD=${{ github.sha }}
      - name: kubectl-simple
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image deployment/key-service key-service=${{ steps.deploy-meta.outputs.tags }} --namespace=retro-board

